config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 6, maximum: 25 }, uniqueness: { case_sensitive: false }
  validates :description, presence: true,
                          length: { minimum: 1, maximum: 350 },
                          uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "L'article a été créé avec succés!"
      redirect_to @article
    else
      render "new"
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "L'article a été mis à jour"
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h2>Les erreurs suivantes ont bloquées l'enregistrement de votre article</h2>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with(model: @article, local: true) do |f| %>
    <p>
      <%= f.label :title, "Titre", class: "form-label" %>
      <%= f.text_field :title, class: "form-control" %>
    </p>
    <p>
      <%= f.label :description, class: "form-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </p>
    <p>
      <%= f.submit "Soumettre", class: "btn btn-primary" %>
    </p>
  <% end %>

app/views/articles/edit.html.erb
<section class="container card p-4">
  <h1 class="card-title text-center border-bottom pb-4 mb-4">Editez votre Article</h1>

  <%= render 'form' %>

  <%= link_to "Annuler et retourner à la liste", articles_path %>
</section>

app/views/articles/index.html.erb
<div class="container">
  <h1>Articles</h1>

  <table>
    <thead>
      <tr>
        <th class="text-center">Title</th>
        <th class="text-center">Description</th>
        <th class="text-center" colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><strong><%= article.title %></strong></td>
        <td><%= article.description %></td>
        <td><%= link_to "Voir", article_path(article) %></td>
        <td><%= link_to "Editer", edit_article_path(article) %></td>
        <td><%= link_to "Supprimer", article_path(article), method: :delete, data: {confirm: "Etes vous certain de vouloir supprimer cet article?"} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <p class="mt-2">
    <%= link_to "Nouveau", new_article_path %>
  </p>
</div>

app/views/articles/new.html.erb
<section class="container card p-4">
  <h1 class="card-title text-center border-bottom pb-4 mb-4">Nouvel Article</h1>

  <%= render 'form' %>

  <%= link_to "retourner à la liste", articles_path %>
</section>

app/views/articles/show.html.erb
<section class="container">
  <h1 class="text-center">Article</h1>

  <div class="article">
    <h2><%= @article.title %></h2>
    <p><%= @article.created_at %></p>
    <p><%= @article.description %></p>
  </div>
  <%= link_to "Editer", edit_article_path(@article) %> |
  <%= link_to "delete", article_path(@article), method: :delete, data: {confirm: "Etes vous certain de vouloir supprimer cet article?"} %> |
  <%= link_to "retourner à la liste", articles_path %>
</section>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
  <%= message %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodevBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>A propos de Todev Blog</h1>

<%= link_to "Accueil", root_path %>
<%= link_to "Aller à la liste", articles_path %> |

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<%= link_to "Aller à la liste", articles_path %> |
<%= link_to "A propos", about_path %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Bienvenue sur <strong>Todev Blog</strong> pour<strong> les passionnés du code</strong>!</h1>
    <p>Change your life and learn to code at one of our campuses around the world.</p>
    <%= link_to "Accéder au Blog", articles_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Accueil", root_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "Blog", articles_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item">
            <%= link_to "A propos", about_path, class: "nav-link text-light" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>